#!/bin/sh

set -eu

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

echo "pre-commit: running all unit tests."
./mvnw -T 1C -q \
  -DfailIfNoTests=false \
  -Dtest="*Test,*Tests,*TestCase" \
  -DexcludedTests="*IT,*IntegrationTest,*E2ETest" \
  test