package com.booker.exceptions;

public enum ErrorCode {
  RESOURCE_NOT_FOUND,
  COVER_ERROR,
  INVALID_ARGUMENT,
  INVALID_CREDENTIALS,
  AUTHENTICATION_FAILED,
  ACCESS_DENIED,
  TYPE_MISMATCH,
  VALIDATION_ERROR,
  INTERNAL_ERROR,

  BUSINESS_RULE_VIOLATION,
  USERNAME_ALREADY_EXISTS,
  EMAIL_ALREADY_EXISTS,
  INCORRECT_PASSWORD,
  INVALID_TOKEN,
  TOKEN_EXPIRED,
  DUPLICATE_REVIEW
}
