CREATE TABLE users (
  id         UUID         PRIMARY KEY DEFAULT uuidv7(),
  name       VARCHAR(100) NOT NULL,
  username   VARCHAR(30)  NOT NULL UNIQUE,
  email      VARCHAR(254) NOT NULL UNIQUE,
  password   VARCHAR(255) NOT NULL,
  bio        VARCHAR(300),
  created_at TIMESTAMP    NOT NULL    DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL    DEFAULT CURRENT_TIMESTAMP
);